backend:
  # Dev backend changes lost on refresh
  # name: test-repo
  
  # GitHub backend without using netlify
  name: github
  repo: ntmk/content-manager
  
  # Netlify backend - uses netlify identities
  # name: git-gateway
  # branch: master # Branch to update on new commit if omitted defaults to master

# used for displaying images in media library
display_url: https://github.com/ntmk/content-manager/
# Media files will be stored in the repo under static/images/uploads
media_folder: "static/images/"
# The src attribute for uploaded media will begin with /images/uploads
public_folder: "/images"

collections:
  - name: "product-page"
    label: "Product Page"
    extension: json
    folder: "static/data"
    create: true
    slug: "{{slug}}"
    preview_path: "/{{slug}}"
    editor:
      preview: true
    fields: 
      - { label: "Test", name: "title", widget: "text", default: "products" }
      - { label: "Products", name: "products", widget: "list", default: [], required: false, fields: [
          { label: "Product Logo", name: "product_logo", widget: "image", required: false },
          { label: "Product Name", name: "product_name", widget: "string" , required: false },
          { label: "Key Points", name: "key_points", widget: "list", required: false, fields: [
            { label: "Key Points", name: "point", widget: "string" , required: false },
          ] },
          { label: 'Button URL', name: "button_url", widget: "string" , required: false },
          { label: "Button Text", name: "button_text", widget: "string" , required: false },
          { label: "Star Rating", name: "star_rating", widget: "select", required: false, options: [1, 2, 3, 3.5, 4, 4.5, 5] },
          { label: "More Info", name: "more_info", widget: "object", required: false, fields: [
            { label: "More Info Title", name: "more_info_title", widget: "string", required: false },
            { label: "Product Image", name: "product_image", widget: "image", required: false },
            { label: "More Info Content", name: "more_info_content", widget: "markdown", required: false },
            { label: "Review Link", name: "review_link", widget: "string", required: false },
            { label: "Site Link", name: "site_link", widget: "string", required: false },
          ] },
          { label: "Reviews", name: "reviews", widget: "list", required: false, fields: [
            { label: "Review Source", name: "review_source", widget: "string", required: false },
            { label: "Review Source URL", name: "source_url", widget: "string", required: false },
            { label: "Quote", name: "quote", widget: "string", required: false },
          ] },
        ] }

