backend:
  # Dev backend changes lost on refresh
  # name: test-repo
  
  # GitHub backend without using netlify
  name: github
  repo: ntmk/content-manager
  
  # Netlify backend - uses netlify identities
  # name: git-gateway
  # branch: master # Branch to update on new commit if omitted defaults to master

# used for displaying images in media library
display_url: https://github.com/ntmk/content-manager/
# Media files will be stored in the repo under static/images/uploads
media_folder: "static/images/"
# The src attribute for uploaded media will begin with /images/uploads
public_folder: "/images"

collections:
  - name: "site-data"
    label: "Site Data"
    extension: json
    folder: "static/data"
    create: true
    slug: "{{slug}}"
    preview_path: "/{{slug}}"
    editor:
      preview: true
    fields: 
      - { label: "Site Name", name: "title", widget: "string" }
      - { label: "Home Page", name: "home", widget: "object", required: false, fields: [
        { label: "Banner Image", name: "banner_image", widget: "image", required: false },
        { label: "Banner Image Alt Text", name: "banner_alt_text", widget: "string", required: false },
        { label: "Title", name: "title", widget: "string" },
        { label: "Position", name: "position", widget: "string", required: false },
        { label: "Quote", name: "quote", widget: "string", required: false },
      ] }
      - { label: "Experience", name: "experience", widget: "object", required: false, fields: [ 
        { label: "Title", name: "title", widget: "string", required: false },
        { label: "Description", name: "description", widget: "text", required: false },
        { label: "Experience list", name: "experience", widget: "list", required: false, fields: [
          { label: "Title", name: "title", required: false},
          { label: "Description", name: "description", widget: "string", required: false },
          { label: "Icon", name: "icon", widget: "string", required: false },
        ] },
      ] }
      - { label: "About", name: "about", widget: "object", required: false, fields: [
        { label: "Title", name: "title", widget: "string" },
        { label: "Description", name: "description", widget: "text", required: false },
        { label: "About Image", name: "about_image", widget: "image", required: false },
        { label: "About list", name: "experience", widget: "list", required: false, fields: [
          { label: "Title", name: "title", required: false},
          { label: "Description", name: "description", widget: "text", required: false },
        ] },
      ]}
      
